### ISSUE TITLE
Error checking-Active Player Tries to Start Game With Less Than 3 Players

### ISSUE THREAD

**Issue by KenMikkalson** [cmsc495fall/Cardczar#12]
Add functionality

**Comment by crimson30** [comment]
Code ready.  Waiting on version control issue before pushing.

**Comment by crimson30** [comment]
Added to RoomActivity:
// CHECK FOR VALID NUMBER OF USERS
        refreshList(view);
        System.out.print("Number of users = "+numusers);
        if (numusers > 2 && numusers < 10) {
