### ISSUE TITLE
Gameover

### ISSUE THREAD

**Issue by crimson30** [cmsc495fall/Cardczar#2]
Need some kind of game over, whether it's an activity, fragment or just an alert dialog.

**Comment by sbholle** [comment]
The issue has been resolved and the code pushed to the repository.

**Comment by sbholle** [comment]
The code merge left a line out. Need to fix.

**Comment by sbholle** [comment]
Kenny, RIchard and I did a test run tonight and the fix worked. Clicking the start new game button took the user back to the main activity screen and did not crash the app.
